# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Story.destroy_all
Character.destroy_all



the_affair = Story.create(name: "The Affair", description: "Amelia Delore has it all. Beauty, wealth and the perfect husband. Unfortunately, she is never satified with her luxurious life and is yearning for a younger man who can please her. She decides to cheat on her husband with a young stockbroker by the name of Johnny Serrano. In this story, Amelia's affair is the cause of someone's death, but who? Who gets killed and who is the killer?",
img_url: "https://s-media-cache-ak0.pinimg.com/originals/d4/02/99/d402995ce7b96c2625f337ad74553c05.jpg")
the_accident = Story.create(name: "The Accident", description: "Vince Neuman is a snake. He's money hungry bastard who only cares about himself and at times, his girlfriend Bethany. A year ago, he got in an accident and almost killed a man. He blamed the man he almost killed. Another serious accident has happened and someone was killed. As usual, Vince is denying the accident, but is he telling the truth or is he just trying to play victim?",  img_url: "https://s-media-cache-ak0.pinimg.com/736x/94/2a/92/942a921e7c1a20d2559a769cab33a1fe.jpg")
the_hitman = Story.create(name: "The Hitman", description:"It was a beautiful night outside the popular Penguin's nightclub. A beautiful woman by the name of Mary Newbelle was the star singer of the night, when there were two gunshots. A man who knew Mary, had been murdered in cold blood. Now Mary, and her protector, Dino, have become suspects. But who has commited the crime and who was killed?", img_url: "http://www.clipartkid.com/images/561/roaring-20s-silhouettes-B9UWfC-clipart.jpg")
dr_jekyll_and_mr_hyde = Story.create(name: "Dr.Jekyll and Mr.Hyde", description:"Dr. Henry Jekyll has been suffering with an interesting, demonic alter ego that exists inside of him. In hopes to hiding it, he develops a serum that ironically causes the alter ego to become stronger and come out as a man by the name of Edward Hyde. Unlike Dr. Jekyll, Edward Hyde is evil,psychotic, and hideous. Without proper control, Jekyll's life gets out of hand when those around him are killed. But by who?", img_url: "http://drjekyllandmrhyde.altervista.org/wp-content/uploads/2014/07/drjekyllmrhyde11.jpg")

eric = Character.create(name: "Eric Stanley", age:"32", nationality: "American", story: the_affair, role: "bystander", description: "Eric Stanley is a charming devil. A wealthy businessman with many connections. Those including many mafia gang leaders and drug lords. He is a master poker player and the fiance of Miss Amelia Delore.", img_url: "http://movie_pal.tripod.com/jimmy-stewart2.jpg")
martin = Character.create(name: "Martin Ciaccone", age:"28", nationality: "Italian-American", story: the_affair, role:"killer", description: "Martin Ciaccone, a Hollywood celebrity and swinger. A natural born athlete, actor, and swinger. He secretly despises the Hollywood elitists and Eric Stanley. As he painfully dwells on broken relationship, he continues to play games.", img_url: "https://s-media-cache-ak0.pinimg.com/originals/03/d5/b9/03d5b9d11bfb32a8b5876f1290c60b99.jpg")
john = Character.create(name: "John Serrano", age:"26", nationality:"Italian-American", story: the_affair, role:"bystander", description: "John Serrano, a stockbroker by day and a member of the Rizzuli mafia by night. He is handsome, wealthy and dangerous. While he is good friends with Eric Stanley, as they used to work together, he is secretly in love with his fiance. Johnny Serrano will not hesitate to make enemies with anyone.",img_url:"http://4.bp.blogspot.com/-rtJJyfrBEek/Vcl8VD1sBFI/AAAAAAAAGgU/yBM6yU7H8P4/s1600/Power1.gif")
amelia = Character.create(name: "Amelia Delore", age:"26", nationality: "Italian-American", story: the_affair, role:"victim", description: "Amelia Delore has been a beauty queen since the age of 8. The beautiful singer became engaged to Eric Stanley, but still longs for the passion she feels when she sings. She has had a history of secret affairs and flings, much like Martin, but refuses to give up Eric. Perhaps she will find love one day.", img_url: "http://filmstarfacts.com/wp-content/uploads/2015/02/Rita-Hayworth-rita-hayworth-30399863-297-300.png")
jennifer = Character.create(name: "Jennifer Moran", age:"25", nationality: "Irish-American", story: the_affair, role: "bystander", description: "Jennifer Moran is a makeup artist for hollywood. She has known Amelia and Martin for a very long time. Like Amelia, Jennifer is also very beautiful, but torn and constantly starves for affection from Martin who cheats on her. Jennifer is quite envious of Amelia, but refuses to love anyone else but Martin. If anyone would interfere with their relationship, she would ruin their lives.", img_url: "http://cdn.collider.com/wp-content/uploads/grace-kelly-01.gif")
donny = Character.create(name: "Donny Perry", age:"30", nationality: "American", story: the_affair,  role: "bystander", description: "Donny is the owner of the most luxurious hotel in Hollywood, The Perry. He is a pretentious young owner, with charm, and a smile that can swoon even the most beautiful of women. Unfortunately, he is not the romantic type. He cares more about money than any living thing on the planet and will do anything to maintain his wealth.", img_url: "http://www.doctormacro.com/Images/McCrea,%20Joel/McCrea,%20Joel_01.jpg")

vince = Character.create(name: "Vince Neuman", age:"28", nationality: "American", story: the_accident, role: "bystander",description:"Vince Neuman is a pretentious, self-absorbed asshole. Although intelligent and handsome, he lacks manners and is careless. He is in a relationship with Ms. Bethany Grant. ", img_url: "http://www.doctormacro.com/Images/Gable,%20Clark/Annex/Annex%20-%20Gable,%20Clark_06.jpg")
george = Character.create(name: "George Tinley", age:"32", nationality: "British", story: the_accident, role: "victim", description: "George Tinley, the British Stallion is known for his looks, athleticism, and arrogance. He is a world class Polo player and charmer. Along with his many fans, he has just as many enemies. In terms of relationships, George doesn't believe in love or committment.", img_url: "https://smhttp-ssl-39255.nexcesscdn.net/wp-content/uploads/2014/10/Young-Cary-Grant-in-Hollywood.jpg")
bethany = Character.create(name: "Bethany Grant", age:"26", nationality: "American", story: the_accident, role:"killer", description: "Bethany Grant is a beautiful actress. The kind of actress who pretends to love and pretends to care. She cares more about her physical appearance, than those who care about her. Unfortunately, her husband isn't aware that she has cheated on him on numerous occasions.", img_url: "http://dameelizabethtaylor.com/blog1/wp-content/uploads/2011/07/vivien-leigh.jpg")
alice = Character.create(name: "Alice Moore", age:"30", nationality: "American", story: the_accident, role: "bystander", description: "A sweet woman whose luck seems to fail everytime she tries to get a new job. Along, with trying to find a man, she finds herself involved in a predicament that could cost her, her life.",img_url:"http://the100.ru/images/actors/id325/4727-kate01.jpg")
daren = Character.create(name: "Daren Steele", age:"29", nationality: "American", story: the_accident, role:"bystander", description:"A Southern stunner whose recklessness seems to get in the way of his daily work and priorities. Just when things start to change for Daren, he becomes the main suspsect of a horrific accident.", img_url:"http://1.bp.blogspot.com/-7axLCR6hE_M/UdjwtI0trZI/AAAAAAAALfk/nK3FQfZMvso/s1600/randy+3.JPG")

patrick = Character.create(name: "Patrick Olson", age:"33", nationality:"American", story: the_hitman, role: "bystander", description:"Patrick Olson is a busy man. He barely has time for his wife, let alone himself. After he finds out that his boss is going to fire him on account of a misunderstanding, he loses his mind. He becomes part of a murder scheme that could ruin his life. The only one who believes his innocence is his wife, Tina.", img_url:"http://silenthollywood.com/sitebuilder/images/Charles_Farrell_111020083-462x600.jpg")
mary = Character.create(name: "Mary Newbelle", age:"24", nationality:"American", story: the_hitman, role:"bystander",description:"A sassy little seductress with the voice of an angel. Mary is a nightclub singer and dancer who gets involved in a murder that occured an hour after her performance. Mary has always claimed to be honest women, but sometimes, even her beauty won't be able to save her from a crime she could have been involved in.", img_url:"https://s-media-cache-ak0.pinimg.com/236x/e3/b4/9f/e3b49f716735373f535b2615bb4d6c6d.jpg")
dino = Character.create(name: "Dino Rogers", age: "46", nationality: "American", story: the_hitman, role:"bystander", description:"Dino is the the bodyguard of the nightclub where Mary sings at. He is one of the toughest, meanest men there is. After a murder was taken place close by, he suddenly becomes a suspect. He never has had a criminal history, but has had a history of violence and abuse. His anger has led him over the edge plenty of times, and could give the police a reason to believe he was somehow involed in the murder.", img_url:"http://images4.fanpop.com/image/photos/20200000/Laurence-Olivier-wuthering-heights-film-20276003-262-291.jpg")
tony = Character.create(name: "Tony Capretti", age: "27", nationality: "Italian-American", story: the_hitman, role:"victim", description:"Tony Capretti is a playboy. The women love him, and the men want to be him. Unfortunately, it seems no one has ever stolen his heart. It wasn't too long ago that his brother was betrayed by a business partner of his. Tony promised revenge, even if it meant his own life in doing so.", img_url:"https://roberttayloractor.files.wordpress.com/2012/06/taylor-1935.jpg")
michael = Character.create(name: "Michael D'Amico", age: "32", nationality: "Italian-American", story: the_hitman, role:"killer", description:"Michael D'Amico is a talented man. He is intelligent, handsome, and romantic. Just like everyone else, he had demons. Those who hurt him and betrayed him. Michael cut ties with his good friend, Johhny Capretti after a series of betrayal, lies and pain he felt was caused by Johnny's actions. Tony promised revenge on Michael, but Michael no longer fears the Caprettis.", img_url: "https://s3-us-west-2.amazonaws.com/find-a-grave-prod/photos/2003/162/7568029_1055455652.jpg")
tina = Character.create(name: "Tina Olson", age: "28", nationality: "American", story: the_hitman, role:"bystander", description: "The wife of Patrick, who spends most of her nights alone. She lives the life of a normal housewife with no children. She has sworn never to cheat or play games, but after feeling so depressed and lonely, another man might satisfy her more than Patrick.", img_url:"https://s-media-cache-ak0.pinimg.com/originals/a2/00/03/a20003bc6104c931989114b9561ef7c4.jpg")

henry = Character.create(name: "Henry Jekyll", age:"36", nationality: "American", story: dr_jekyll_and_mr_hyde, role: "bystander", description:"A brilliant, handsome doctor with a hidden demon inside him. He tries to create a serum to hide the demon inside him, but ironically, it transforms him into Mr. Hyde. Mr. Hyde is a monstrosity created by the demon inside him.", img_url:"http://www.doctormacro.com/Images/Mitchum,%20Robert/Annex/Annex%20-%20Mitchum,%20Robert_04.jpg")
edward = Character.create(name: "Edward Hyde", age: "36", nationality: "American", story: dr_jekyll_and_mr_hyde, role: "killer", description:"The repulsive, hideous monster that appears after Dr.Jekyll drinks the serum.", img_url:"http://kingofwallpapers.com/robert-mitchum/robert-mitchum-006.jpg")
ivy = Character.create(name: "Ivy Pearson", age: "27",nationality: "American", story: dr_jekyll_and_mr_hyde, role: "victim", description:"An attractive barmaid who is lovestruck by Dr. Jekyll. She shares the same feelings at Dr. Jekyll, but not by Mr. Hyde. Unfortunately, Mr. Hyde refuses to take no for an answer and forces himself on her. She is eventually killed by Mr. Hyde.", img_url:"http://www.doctormacro.com/Images/Bacall,%20Lauren/Annex/Annex%20-%20Bacall,%20Lauren_01.jpg")
muriel = Character.create(name: "Muriel Carew", age: "28", nationality: "American", story: dr_jekyll_and_mr_hyde, role: "bystander",description:"The beautiful fiancee of Dr. Jekyll and daughter of Brigadier General Sir Danvers Carew.", img_url:"https://s-media-cache-ak0.pinimg.com/236x/56/94/f0/5694f0559bba24f35ad9d7abfafb4983.jpg")
dr_john = Character.create(name: "Dr.John Lanyon", age: "38", nationality: "American", story: dr_jekyll_and_mr_hyde, role:"bystander", description:"A loyal colleage of Dr. Jekyll, who tries to save Dr.Jekyll from Mr. Hyde.", img_url:"http://image.vam.synacor.com.edgesuite.net/49/01/49015fff406f6e1b95208c2f42283c8e2a1a498a/w=255,h=383,crop=auto/?app=syndex&sig=ab1462bcb161177cbf4f9fe1af3fb6ee844f0b08716ebe745edf23ce662cbc23")
